services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks:
      - mle_network
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant:/qdrant/storage
    environment:
      - ENV_VARIABLE=value

  ollama:
    image: ollama/ollama
    container_name: ollama
    networks:
      - mle_network
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  load_vector_service:
    build: ./load_vector_service
    container_name: load_vector_service
    networks:
      - mle_network
    depends_on:
      - qdrant
    ports:
      - "5002:5002"
    volumes:
      - huggingface_cache:/root/.cache/huggingface 


  llm_api_service:
    build: ./llm_api_service
    container_name: llm_api_service
    networks:
      - mle_network
    depends_on:
      - ollama
      - load_vector_service
    ports:
      - "5003:5003"
    environment:
      - MODEL_NAME=llama3.2:3b

volumes:
  ollama:
  qdrant:
  huggingface_cache:

networks:
  mle_network:
    name: mle_network
    driver: bridge
  default:
    external: false
    name: mle_network