

services:
  vector_db:
    image: milvusdb/milvus:latest
    container_name: milvus
    ports:
      - "19530:19530"

  load_vector_service:
    build: ./load_vector_service
    container_name: load_vector_service
    ports:
      - "8000:8000"

  llm_api_service:
    build: ./llm_api_service
    container_name: llm_api_service
    ports:
      - "8001:8000"
