

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"

  load_vector_service:
    build: ./load_vector_service
    container_name: load_vector_service
    ports:
      - "8000:8000"

  llm_api_service:
    build: ./llm_api_service
    container_name: llm_api_service
    ports:
      - "8001:8000"
